# Generated by Django 3.1.4 on 2020-12-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('nazione', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Autore',
                'verbose_name_plural': 'Autori',
            },
        ),
        migrations.CreateModel(
            name='Editori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societa', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Editore',
                'verbose_name_plural': 'Editori',
            },
        ),
        migrations.CreateModel(
            name='Generi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Genere',
                'verbose_name_plural': 'Generi',
            },
        ),
        migrations.CreateModel(
            name='Libri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=16)),
                ('quantita', models.IntegerField(default=0)),
                ('prezzo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libri', to='libreria.autori')),
                ('editore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libri_per_editore', to='libreria.editori')),
                ('genere', models.ManyToManyField(related_name='libri_per_genere', to='libreria.Generi')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libri',
            },
        ),
    ]
