# Generated by Django 3.1.4 on 2020-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libri',
            name='copertina',
            field=models.ImageField(null=True, upload_to='cover'),
        ),
    ]
