# Generated by Django 3.1.4 on 2020-12-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_libri_copertina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libri',
            name='copertina',
        ),
    ]
