# Generated by Django 3.2.4 on 2021-06-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_libri_disponibile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libri',
            options={'ordering': ('titolo', 'autore', 'editore'), 'verbose_name': 'Libro', 'verbose_name_plural': 'Libri'},
        ),
    ]
